apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  namespace: convenientstore
  labels:
    app: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/user02-delivery:v1
          ports:
            - containerPort: 8080
          # resources:
          #   limits:
          #     cpu: 1000m
          #   requests:
          #     cpu: 500m
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          # args:
          #   - /bin/sh
          #   - -c
          #   - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            # exec:
            #   command:
            #     - cat
            #     - /tmp/healthy
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5