apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: convenientstore
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/user02-order:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: api.url.delivery
              valueFrom:
                configMapKeyRef:
                  name: convenientstore-config
                  key: api.url.delivery
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5